#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --mem=240G

#SBATCH -J BluePyOpt_YT
#SBATCH -p debug
#SBATCH -t 00:30:00
#SBATCH --account=csd403


#module purge
#module load slurm
#module load gcc
#module load openmpi




#. /home/wuy2/.bash_profile
#conda activate MET

#module load python39

. /home/wuy2/2022_0801_all_in_one/blue2/bin/activate

SCOOP_WRAPPER=/home/yuantingwu/2022_0830_ipp/wrapper_venv.sh

export INPUTFILE1=`pwd`/RUN_THIS_FILE_scoop_v8_seq.py
export INPUTFILE2=`pwd`/log_evaluator_scoop_v9.py



#python making_feature_file_v8.py
#python modding_swc_v8.py

scontrol show hostnames > hostfile


#python -m scoop  --hostfile hostfile -n ${SLURM_NTASKS} --python-interpreter=$SCOOP_WRAPPER $INPUTFILE1 0 1 1
python -m scoop --hostfile hostfile -n ${SLURM_NTASKS} --python-interpreter=$SCOOP_WRAPPER $INPUTFILE2 0 6 1
